homeassistant:
  name: CetiAlpha Ⅴ
  latitude: 42.416884
  longitude: -71.083512
  elevation: 13
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

frontend:
lovelace:
        mode: yaml

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
http:
        api_password: !secret http__api_password


discovery:

history:
logbook:
map:
sun:

sensor:
  - platform: waze_travel_time
    name: Time to work
    origin: 26 Quincy st, Malden, MA
    destination: 2 Canal Park, Cambridge, MA
    region: 'US'

tts:
  - platform: google

nest:
        client_id: !secret nest__client_id
        client_secret: !secret nest__client_secret

mqtt:
        broker: localhost
        username: !secret mqtt__username
        password: !secret mqtt__password

light:
        - platform: tplink
          name: sethlamp
          host: 10.1.2.1

device_tracker:
  - platform: ddwrt
    host: 10.1.1.1
    username: ddwrt__username
    password: ddwrt__password
    interval_seconds: 30
    new_device_defaults:
      track_new_devices: false

weather:
  - platform: openweathermap
    api_key: !secret openweathermap__api_key
